-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("QT_QUICK_CONTROLS_STYLE", "org.kde.desktop")

hl.env("GTK_THEME", "Adwaita:dark")

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = 1,
})

hl.window_rule({
    name = "panel-style",
    match = { title = "^(panel)$" },
    float = true,
    move = { "0", "5" }
})

hl.window_rule({
    name = "launcher-style",
    match = { title = "^(launcher)$" },
    float = true,
    pin = true,
    animation = "slide top",
    move = { "(monitor_w/2-window_w/2)", "50" }
})

hl.window_rule({
    name = "netmenu-style",
    match = { title = "^(netmenu)$" },
    float = true,
    pin = true,
    animation = "slide top",
    move = { "(monitor_w-window_w-10)", "50" }
})

hl.window_rule({
    name = "wifilist-style",
    match = { title = "^(wifilist)$" },
    float = true,
    pin = true,
    animation = "slide top",
    move = { "(monitor_w-window_w-200)", "50" }
})

hl.window_rule({
    name = "btlist-style",
    match = { title = "^(btlist)$" },
    float = true,
    pin = true,
    animation = "slide top",
    move = { "(monitor_w-window_w-200)", "50" }
})

hl.window_rule({
    name = "powermenu-style",
    match = { title = "^(powermenu)$" },
    float = true,
    pin = true,
    animation = "slide top",
    move = { "(monitor_w-window_w-10)", "50" }
})

hl.window_rule({
    name = "volumeosd-style",
    match = { title = "^(volumeosd)$" },
    float = true,
    pin = true,
    animation = "slide bottom",
    move = { "(monitor_w/2-window_w/2)", "(monitor_h-150)" }
})

hl.window_rule({
    name = "powerconfirm-style",
    match = { title = "^(powerconfirm)$" },
    float = true,
    pin = true,
    move = { "(monitor_w/2-window_w/2)", "(monitor_h/2-window_h/2)" }
})

hl.window_rule({
    name = "clipboard-style",
    match = { title = "^(clipboard)$" },
    float = true,
    pin = true,
    animation = "slide top",
    move = { "(monitor_w/2-window_w/2)", "50" }
})


hl.bind("SUPER" .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind("SUPER" .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind("SUPER" .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind("SUPER" .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind("SUPER" .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind("SUPER" .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind("SUPER" .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind("SUPER" .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind("SUPER" .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind("SUPER" .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

hl.bind("SUPER + SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind("SUPER + SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind("SUPER + SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind("SUPER + SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind("SUPER + SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind("SUPER + SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind("SUPER + SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind("SUPER + SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind("SUPER + SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind("SUPER + SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

hl.bind("SUPER" .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind("SUPER" .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind("SUPER" .. " + " .. "TAB", hl.dsp.focus({ workspace = "previous" }))

hl.bind("SUPER" .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind("SUPER" .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind("SUPER" .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind("SUPER" .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

hl.bind("SUPER + SHIFT" .. " + " .. "left", hl.dsp.window.move({ direction = "l" }))

hl.bind("SUPER + SHIFT" .. " + " .. "right", hl.dsp.window.move({ direction = "r" }))

hl.bind("SUPER + SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "u" }))

hl.bind("SUPER + SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "d" }))

hl.bind("SUPER" .. " + " .. "D", hl.dsp.exec_cmd("qs ipc call launcher toggle"))

hl.bind("SUPER" .. " + " .. "Return", hl.dsp.exec_cmd("kitty"))

hl.bind("SUPER" .. " + " .. "Q", hl.dsp.window.close())

hl.bind("SUPER" .. " + " .. "M", hl.dsp.exit())

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && qs ipc call volumeosd trigger"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && qs ipc call volumeosd trigger"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && qs ipc call volumeosd trigger"), { locked = true })

hl.bind("Print", hl.dsp.exec_cmd("grim ~/Pictures/Screenshots/$(date +%Y%m%d_%H%M%S).png"))

hl.bind("SUPER" .. " + " .. "Print", hl.dsp.exec_cmd("grim -g $(slurp)-| wl-copy"))

hl.bind("SUPER + SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd("grim -g $(slurp) ~/Pictures/Screenshots/$(date +%Y%m%d_%H%M%S).png"))

hl.bind("SUPER" .. " + " .. "V", hl.dsp.exec_cmd("qs ipc call clipboard toggle"))

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 2,
        col = {
            inactive_border = "rgb(111111)",
            active_border = "rgb(3b4261)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 8,
    },
})

hl.config({
    misc = {
        disable_hyprland_guiutils_check = true,
    },
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("swaybg -i /home/christopher/.config/hypr/wallpaper.jpg -m fill")
    hl.exec_cmd("quickshell")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
