env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QUICK_CONTROLS_STYLE,org.kde.desktop

monitor=,preferred,auto,1

windowrule = float on, match:title ^(panel)$
windowrule = move 0 5, match:title ^(panel)$

windowrule = float on, match:title ^(launcher)$
windowrule = animation slide top, match:title ^(launcher)$
windowrule = move (monitor_w/2-window_w/2) 50, match:title ^(launcher)$
windowrule = border_size 0, match:title ^(launcher)$

windowrule = float on, match:title ^(netmenu)$
windowrule = animation slide top, match:title ^(netmenu)$
windowrule = move (monitor_w-window_w-10) 50, match:title ^(netmenu)$
windowrule = border_size 0, match:title ^(netmenu)$

windowrule = float on, match:title ^(wifilist)$
windowrule = animation slide top, match:title ^(wifilist)$
windowrule = move (monitor_w-window_w-200) 50, match:title ^(wifilist)$
windowrule = border_size 0, match:title ^(wifilist)$

windowrule = float on, match:title ^(btlist)$
windowrule = animation slide top, match:title ^(btlist)$
windowrule = move (monitor_w-window_w-200) 50, match:title ^(btlist)$
windowrule = border_size 0, match:title ^(btlist)$

windowrule = float on, match:title ^(powermenu)$
windowrule = animation slide top, match:title ^(powermenu)$
windowrule = move (monitor_w-window_w-10) 50, match:title ^(powermenu)$
windowrule = border_size 0, match:title ^(powermenu)$

windowrule = float on, match:title ^(volumeosd)$
windowrule = move (monitor_w/2-window_w/2) (monitor_h-150), match:title ^(volumeosd)$
windowrule = border_size 0, match:title ^(volumeosd)$
windowrule = animation slide, match:title ^(volumeosd)$

windowrule = float on, match:title ^(powerconfirm)$
windowrule = move (monitor_w/2-window_w/2) (monitor_h/2-window_h/2), match:title ^(powerconfirm)$
windowrule = border_size 0, match:title ^(powerconfirm)$

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland
exec-once = systemctl --user start xdg-desktop-portal-hyprland
exec-once = swaybg -i /home/christopher/.config/hypr/wallpaper.jpg -m fill
exec-once = quickshell
exec-once = hypridle

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6
bind = SUPER, 7, workspace, 7
bind = SUPER, 8, workspace, 8
bind = SUPER, 9, workspace, 9
bind = SUPER, 0, workspace, 10

bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
bind = SUPER SHIFT, 6, movetoworkspace, 6
bind = SUPER SHIFT, 7, movetoworkspace, 7
bind = SUPER SHIFT, 8, movetoworkspace, 8
bind = SUPER SHIFT, 9, movetoworkspace, 9
bind = SUPER SHIFT, 0, movetoworkspace, 10

bind = SUPER, mouse_down, workspace, e+1
bind = SUPER, mouse_up, workspace, e-1

bind = SUPER, TAB, workspace, previous

bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

bind = SUPER SHIFT, left, movewindow, l
bind = SUPER SHIFT, right, movewindow, r
bind = SUPER SHIFT, up, movewindow, u
bind = SUPER SHIFT, down, movewindow, d

bind = SUPER, D, exec, qs ipc call launcher toggle
bind = SUPER, Return, exec, kitty
bind = SUPER, Q, killactive
bind = SUPER, M, exit

bindl = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && qs ipc call volumeosd trigger
bindl = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && qs ipc call volumeosd trigger
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && qs ipc call volumeosd trigger

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.inactive_border = rgb(111111)
    col.active_border = rgb(3b4261)
}

decoration {
    rounding = 8
}
